In [18]:
import numpy as np #importing packages

### 1. Create

In [185]:
data = np.random.rand(2, 3, 4) # 2 arrays, 3 rows, 4 col's
zeros = np.zeros((2, 3, 4)) # 2 arrays, 3 rows, 4 col's
full = np.full((2, 3, 4), 5) # 2 arrays, 3 rows , 4 col's, (only 5's)
ones = np.ones((2, 3 , 4))  #2 arrays, 3 rows, 4 col's ,(default 1)

In [41]:
arr = np.array([1,2,3]) # 1 D array
arr 

array([1, 2, 3])

In [49]:
arr2 = np.array([[1, 4, 20], [3, 10, 50]]) # 2 D array
arr2

array([[ 1,  4, 20],
       [ 3, 10, 50]])

### 2. Read

In [62]:
# data = np.random.rand(2, 3, 4) # 2 arrays, 3 rows, 4 col's
shape = data.shape # shape
size = data.size # szie
types = data.dtype # data Type

In [63]:
shape # num of arrays, rows, col

(2, 3, 4)

In [64]:
size # Numebr of elements in the array

24

In [67]:
types # data Type of the array

dtype('float64')

In [69]:
data # random array's stored in 'data' variable

array([[[0.25920896, 0.59521875, 0.97325988, 0.7174293 ],
        [0.10885041, 0.60958975, 0.72783854, 0.20996552],
        [0.67658056, 0.16648566, 0.0735755 , 0.81518414]],

       [[0.37225654, 0.82163239, 0.23573985, 0.81888704],
        [0.79554143, 0.16169158, 0.71505377, 0.07305332],
        [0.61323216, 0.14854311, 0.42661133, 0.37037945]]])

In [83]:
data.shape

(2, 3, 4)

In [97]:
# Slicing
arr = data[0] # 0th array list
slicer = data[0][0:2] # 0th array print first 2 rows only
reverse = data[-1] # Bottom array
single_element = data[0][0][2] # Picking out each value from the array
slicer

array([[0.25920896, 0.59521875, 0.97325988, 0.7174293 ],
       [0.10885041, 0.60958975, 0.72783854, 0.20996552]])

### 3. Update

In [105]:
list1 = np.random.rand(2, 3 ,5) # Random array
list2 = np.random.rand(2, 3, 5) # Random array

In [115]:
add = np.add(list1, list2) # add list1 & list 2
sub = np.subtract(list1, list2) # subtract
mul = np.multiply(list1, list2) # multiply
div = np.divide(list1, list2) # divide

In [130]:
# SAPLEMM
sqrt = np.sqrt(23) # squaRe root
ab = np.abs(-10) # absolute value
power = np.power(2, 5) # power of 2 raise to 5
log = np.log(1.44) # log of 1.44
exp = np.exp([2,3]) # Exponential of 2,3
mins = np.min(list1) # min value of list1
maxs = np.max(list2) # max value of list2

In [131]:
exp # exponential value

array([ 7.3890561 , 20.08553692])

In [133]:
data

array([[[0.25920896, 0.59521875, 0.97325988, 0.7174293 ],
        [0.10885041, 0.60958975, 0.72783854, 0.20996552],
        [0.67658056, 0.16648566, 0.0735755 , 0.81518414]],

       [[0.37225654, 0.82163239, 0.23573985, 0.81888704],
        [0.79554143, 0.16169158, 0.71505377, 0.07305332],
        [0.61323216, 0.14854311, 0.42661133, 0.37037945]]])

In [135]:
data[0][0][0] = 500 # updating value

In [137]:
data # updated 'data'

array([[[5.00000000e+02, 5.95218753e-01, 9.73259880e-01, 7.17429298e-01],
        [1.08850411e-01, 6.09589751e-01, 7.27838538e-01, 2.09965515e-01],
        [6.76580562e-01, 1.66485657e-01, 7.35754985e-02, 8.15184136e-01]],

       [[3.72256538e-01, 8.21632393e-01, 2.35739847e-01, 8.18887045e-01],
        [7.95541431e-01, 1.61691580e-01, 7.15053771e-01, 7.30533245e-02],
        [6.13232162e-01, 1.48543106e-01, 4.26611329e-01, 3.70379454e-01]]])

In [139]:
np.sort(data) # Normal Sort or sort by row's by default axis = 0

array([[[5.95218753e-01, 7.17429298e-01, 9.73259880e-01, 5.00000000e+02],
        [1.08850411e-01, 2.09965515e-01, 6.09589751e-01, 7.27838538e-01],
        [7.35754985e-02, 1.66485657e-01, 6.76580562e-01, 8.15184136e-01]],

       [[2.35739847e-01, 3.72256538e-01, 8.18887045e-01, 8.21632393e-01],
        [7.30533245e-02, 1.61691580e-01, 7.15053771e-01, 7.95541431e-01],
        [1.48543106e-01, 3.70379454e-01, 4.26611329e-01, 6.13232162e-01]]])

In [140]:
np.sort(data, axis = 1) # sorting by col's

array([[[7.35754985e-02, 1.66485657e-01, 6.09589751e-01, 7.27838538e-01],
        [1.08850411e-01, 2.09965515e-01, 6.76580562e-01, 8.15184136e-01],
        [5.95218753e-01, 7.17429298e-01, 9.73259880e-01, 5.00000000e+02]],

       [[7.30533245e-02, 1.61691580e-01, 4.26611329e-01, 6.13232162e-01],
        [1.48543106e-01, 3.70379454e-01, 7.15053771e-01, 7.95541431e-01],
        [2.35739847e-01, 3.72256538e-01, 8.18887045e-01, 8.21632393e-01]]])

In [142]:
data.shape # current data array size is (2, 3, 4)

(2, 3, 4)

In [147]:
# Reshaping an array usinf reshape fn
reshaping = data.reshape(2, 1, -1) # use -1 to make it understand 'IDC' put some valeu
reshaping

array([[[5.95218753e-01, 7.17429298e-01, 9.73259880e-01, 5.00000000e+02,
         1.08850411e-01, 2.09965515e-01, 6.09589751e-01, 7.27838538e-01,
         7.35754985e-02, 1.66485657e-01, 6.76580562e-01, 8.15184136e-01]],

       [[2.35739847e-01, 3.72256538e-01, 8.18887045e-01, 8.21632393e-01,
         7.30533245e-02, 1.61691580e-01, 7.15053771e-01, 7.95541431e-01,
         1.48543106e-01, 3.70379454e-01, 4.26611329e-01, 6.13232162e-01]]])

In [150]:
reshaping.shape # after reshape its 2, 1, 12 

(2, 1, 12)

In [167]:
# Append
zeros = np.zeros((1, 3, 5))
zeros # an array of only 0's
zeros = np.append(zeros, [2, 3])
zeros # appending at bottom 2, 3 to array of 0's

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 3.])

In [168]:
zeros = np.insert(zeros, 0, 10) # inserting an element into a specified index of an array

In [169]:
zeros

array([10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  2.,  3.])

### 4. Delete

In [186]:
data

array([[[0.92711105, 0.26636638, 0.93210321, 0.45399704],
        [0.64403413, 0.60155134, 0.66736699, 0.18814387],
        [0.93248771, 0.96442675, 0.78126528, 0.25894953]],

       [[0.9566165 , 0.93905741, 0.83952148, 0.40795434],
        [0.04432057, 0.20669722, 0.17489184, 0.44802468],
        [0.96698866, 0.29115561, 0.72573794, 0.25108448]]])

In [187]:
np.delete(data, 0, axis = 1) # delete first row from 1st & 2nd array

array([[[0.64403413, 0.60155134, 0.66736699, 0.18814387],
        [0.93248771, 0.96442675, 0.78126528, 0.25894953]],

       [[0.04432057, 0.20669722, 0.17489184, 0.44802468],
        [0.96698866, 0.29115561, 0.72573794, 0.25108448]]])

## Saving & Loading the array

In [189]:
np.save('new_array', data) # save the array in .npy file

In [192]:
data = np.load('new_array.npy') # loading the array

In [193]:
data

array([[[0.92711105, 0.26636638, 0.93210321, 0.45399704],
        [0.64403413, 0.60155134, 0.66736699, 0.18814387],
        [0.93248771, 0.96442675, 0.78126528, 0.25894953]],

       [[0.9566165 , 0.93905741, 0.83952148, 0.40795434],
        [0.04432057, 0.20669722, 0.17489184, 0.44802468],
        [0.96698866, 0.29115561, 0.72573794, 0.25108448]]])

In [225]:
!git status

On branch numpy
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Untitled.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [226]:
!git commit -m "Numpy revision added"

On branch numpy
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Untitled.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [228]:
!git push -u origin numpy

'git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


In [229]:
!git remote add origin 'https://github.com/joelsiby02/Pandas-Revision.git'

error: remote origin already exists.
